services:
  leshan:
    image: leshan/leshan-server-demo:latest
    container_name: swms-leshan-demo
    ports:
      - "8081:8080"
      - "5683:5683/udp"
      - "5684:5684/udp"
    restart: unless-stopped

  registry:
    build:
      context: ./registry
      dockerfile: Dockerfile
    container_name: swms-device-registry
    ports:
      - "8090:8090"
    restart: unless-stopped
